//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alternative.AltServSpace {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Alternate.WindowsService", ConfigurationName="AltServSpace.IAlternate")]
    public interface IAlternate {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Alternate.WindowsService/IAlternate/GetInterval", ReplyAction="http://Alternate.WindowsService/IAlternate/GetIntervalResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="start")]
        int GetInterval(out int end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Alternate.WindowsService/IAlternate/Login", ReplyAction="http://Alternate.WindowsService/IAlternate/LoginResponse")]
        string Login(string src, [System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Alternate.WindowsService/IAlternate/Query", ReplyAction="http://Alternate.WindowsService/IAlternate/QueryResponse")]
        string Query(string cert, [System.ServiceModel.MessageParameterAttribute(Name="query")] string query1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAlternateChannel : Alternative.AltServSpace.IAlternate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlternateClient : System.ServiceModel.ClientBase<Alternative.AltServSpace.IAlternate>, Alternative.AltServSpace.IAlternate {
        
        public AlternateClient() {
        }
        
        public AlternateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlternateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlternateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlternateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetInterval(out int end) {
            return base.Channel.GetInterval(out end);
        }
        
        public string Login(string src, string login1, string password) {
            return base.Channel.Login(src, login1, password);
        }
        
        public string Query(string cert, string query1) {
            return base.Channel.Query(cert, query1);
        }
    }
}
