//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34014
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alternative {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonText() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alternative.CommonText", typeof(CommonText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ для передачи в типографию успешно создан.
        /// </summary>
        internal static string AdmAsyncKeyPressCreated {
            get {
                return ResourceManager.GetString("AdmAsyncKeyPressCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл ключа или путь к нему успешно изменен..
        /// </summary>
        internal static string AdmAsyncKeyPressEdited {
            get {
                return ResourceManager.GetString("AdmAsyncKeyPressEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ключ для передачи в платежную систему успешно создан..
        /// </summary>
        internal static string AdmAsyncKeySaleCreated {
            get {
                return ResourceManager.GetString("AdmAsyncKeySaleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл ключа для передачу в платежную систему успешно изменен..
        /// </summary>
        internal static string AdmAsyncKeySaleEdited {
            get {
                return ResourceManager.GetString("AdmAsyncKeySaleEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новое ключевое слово успешно создано..
        /// </summary>
        internal static string AdmHashCreated {
            get {
                return ResourceManager.GetString("AdmHashCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл ключевого слова или путь к нему успешно изменен..
        /// </summary>
        internal static string AdmHashWordEdited {
            get {
                return ResourceManager.GetString("AdmHashWordEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление проекта.
        /// </summary>
        internal static string CapDeleteProject {
            get {
                return ResourceManager.GetString("CapDeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование файла или пути для внешнего ключа.
        /// </summary>
        internal static string CapEditAsyncKey {
            get {
                return ResourceManager.GetString("CapEditAsyncKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактрование файла или пути Hash.
        /// </summary>
        internal static string CapEditHasKey {
            get {
                return ResourceManager.GetString("CapEditHasKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение данных.
        /// </summary>
        internal static string CapMsgUnsaveData {
            get {
                return ResourceManager.GetString("CapMsgUnsaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание нового ключа.
        /// </summary>
        internal static string CapNewAsyncKey {
            get {
                return ResourceManager.GetString("CapNewAsyncKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание нового ключевого слова.
        /// </summary>
        internal static string CapNewHash {
            get {
                return ResourceManager.GetString("CapNewHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя входа.
        /// </summary>
        internal static string ClmS_LOGIN {
            get {
                return ResourceManager.GetString("ClmS_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string ClmS_NAME {
            get {
                return ResourceManager.GetString("ClmS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        internal static string ClmS_PASS {
            get {
                return ResourceManager.GetString("ClmS_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Префикс.
        /// </summary>
        internal static string ClmS_PREF {
            get {
                return ResourceManager.GetString("ClmS_PREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание нового дизайна.
        /// </summary>
        internal static string DesignFormHeaderCreate {
            get {
                return ResourceManager.GetString("DesignFormHeaderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование дизайна.
        /// </summary>
        internal static string DesignFormHeaderEdit {
            get {
                return ResourceManager.GetString("DesignFormHeaderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата активации.
        /// </summary>
        internal static string DHActivated {
            get {
                return ResourceManager.GetString("DHActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дизайн.
        /// </summary>
        internal static string DHDesign {
            get {
                return ResourceManager.GetString("DHDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершение действия.
        /// </summary>
        internal static string DHEnd {
            get {
                return ResourceManager.GetString("DHEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номинал.
        /// </summary>
        internal static string DHFace {
            get {
                return ResourceManager.GetString("DHFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доп. поле 1.
        /// </summary>
        internal static string DHField_1 {
            get {
                return ResourceManager.GetString("DHField_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Доп. поле 2.
        /// </summary>
        internal static string DHField_2 {
            get {
                return ResourceManager.GetString("DHField_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало действия.
        /// </summary>
        internal static string DHFrom {
            get {
                return ResourceManager.GetString("DHFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИД.
        /// </summary>
        internal static string DHid {
            get {
                return ResourceManager.GetString("DHid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Юр. лицо.
        /// </summary>
        internal static string DHJuristic {
            get {
                return ResourceManager.GetString("DHJuristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        internal static string DHName {
            get {
                return ResourceManager.GetString("DHName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер.
        /// </summary>
        internal static string DHNumber {
            get {
                return ResourceManager.GetString("DHNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата.
        /// </summary>
        internal static string DHOperDate {
            get {
                return ResourceManager.GetString("DHOperDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция.
        /// </summary>
        internal static string DHOperType {
            get {
                return ResourceManager.GetString("DHOperType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платежка.
        /// </summary>
        internal static string DHPayment {
            get {
                return ResourceManager.GetString("DHPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пин-код.
        /// </summary>
        internal static string DHPin {
            get {
                return ResourceManager.GetString("DHPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена продажи.
        /// </summary>
        internal static string DHSale {
            get {
                return ResourceManager.GetString("DHSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        internal static string DHStatus {
            get {
                return ResourceManager.GetString("DHStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка введенных значений.
        /// </summary>
        internal static string EMsgCheckValue {
            get {
                return ResourceManager.GetString("EMsgCheckValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточки входящие в проект будут удалены!
        ///Вместе с карточками будут удлаены журналы, с ними связанные!
        ///Вы уверены,что хотите этого?.
        /// </summary>
        internal static string MsgCardOfProjectDel {
            get {
                return ResourceManager.GetString("MsgCardOfProjectDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние платежа.
        /// </summary>
        internal static string MsgCardState {
            get {
                return ResourceManager.GetString("MsgCardState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будет сформирован файл для передачи карточек в типографию.
        ///С этого момента, удаление карточек из проекта станет невозможным !.
        /// </summary>
        internal static string MsgCardUloadToPress {
            get {
                return ResourceManager.GetString("MsgCardUloadToPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточки успешно выгружены в файл, для передачи в типографию.
        ///Открыть расположение файла?.
        /// </summary>
        internal static string MsgCardUnloadedToPress {
            get {
                return ResourceManager.GetString("MsgCardUnloadedToPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя доступа к базе было изменено.
        ///Переустановите свой сертификат доступа..
        /// </summary>
        internal static string MsgChangedLoginKey {
            get {
                return ResourceManager.GetString("MsgChangedLoginKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предыдущий ключ будет удален!!!
        ///Вы уверены, что хотите этого?.
        /// </summary>
        internal static string MsgCreateNewAsyncKey {
            get {
                return ResourceManager.GetString("MsgCreateNewAsyncKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предыдущее ключевое слово будет удалено!
        ///Вы уверены, что хотите это сделать?.
        /// </summary>
        internal static string MsgCreateNewHash {
            get {
                return ResourceManager.GetString("MsgCreateNewHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание!
        ///Текущее имя входа в систему будет изменено! Это означает,что 
        ///изменится сертификат доступа и всем клиентам базы данных
        ///нужно будет переустановить сертификаты!.
        /// </summary>
        internal static string MsgDeleteLoginKey {
            get {
                return ResourceManager.GetString("MsgDeleteLoginKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбранные проекты будут удалены!
        ///Вы уверены,что хотите этого?.
        /// </summary>
        internal static string MsgDeleteProject {
            get {
                return ResourceManager.GetString("MsgDeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элемент справочника будет удален!
        ///Вы уверены,что хотите этого?.
        /// </summary>
        internal static string MsgDictionaryElementDel {
            get {
                return ResourceManager.GetString("MsgDictionaryElementDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл ключа или путь к нему будет изменен!
        ///Вы уверены,что хотите этого?.
        /// </summary>
        internal static string MsgEditAsyncKey {
            get {
                return ResourceManager.GetString("MsgEditAsyncKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл ключевого слова или путь к нему будет изменен!
        ///Вы уверены,что хотите этого?.
        /// </summary>
        internal static string MsgEditHashKey {
            get {
                return ResourceManager.GetString("MsgEditHashKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение будет удалено! 
        ///Вы уверены,что хотите этого?.
        /// </summary>
        internal static string MsgImageDel {
            get {
                return ResourceManager.GetString("MsgImageDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные не сохранены !
        ///Продолжить редактирование ?.
        /// </summary>
        internal static string MsgUnsaveData {
            get {
                return ResourceManager.GetString("MsgUnsaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление объекта.
        /// </summary>
        internal static string ObjectDel {
            get {
                return ResourceManager.GetString("ObjectDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        internal static string PrBtnSave {
            get {
                return ResourceManager.GetString("PrBtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        internal static string PrBtnUpdate {
            get {
                return ResourceManager.GetString("PrBtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка файла прошла успешно!.
        /// </summary>
        internal static string PrCardListIsOk {
            get {
                return ResourceManager.GetString("PrCardListIsOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить проект № {0}.
        /// </summary>
        internal static string PrEditForm {
            get {
                return ResourceManager.GetString("PrEditForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать новый проект.
        /// </summary>
        internal static string PrNewForm {
            get {
                return ResourceManager.GetString("PrNewForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список серверов баз данных.
        /// </summary>
        internal static string TAppServersList {
            get {
                return ResourceManager.GetString("TAppServersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выгрузка карточек в типографию.
        /// </summary>
        internal static string TitleCardUnloadToPress {
            get {
                return ResourceManager.GetString("TitleCardUnloadToPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание нового пользователя.
        /// </summary>
        internal static string UserFormHeaderCreate {
            get {
                return ResourceManager.GetString("UserFormHeaderCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование нового пользователя.
        /// </summary>
        internal static string UserFormHeaderEdit {
            get {
                return ResourceManager.GetString("UserFormHeaderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщение.
        /// </summary>
        internal static string UserFormMessage {
            get {
                return ResourceManager.GetString("UserFormMessage", resourceCulture);
            }
        }
    }
}
