//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34003
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alternative {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMsg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMsg() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alternative.ErrorMsg", typeof(ErrorMsg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при редактировании ключевого слова.
        /// </summary>
        internal static string EAdmEditHash {
            get {
                return ResourceManager.GetString("EAdmEditHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при получении ключевого слова.
        /// </summary>
        internal static string EAdmGetHash {
            get {
                return ResourceManager.GetString("EAdmGetHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания ключа для типографии..
        /// </summary>
        internal static string EAdmKeyPressAsync {
            get {
                return ResourceManager.GetString("EAdmKeyPressAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при редактировании данных ключа..
        /// </summary>
        internal static string EAdmKeyPressEditAsync {
            get {
                return ResourceManager.GetString("EAdmKeyPressEditAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при получении данных ключа..
        /// </summary>
        internal static string EAdmKeyPressGetAsync {
            get {
                return ResourceManager.GetString("EAdmKeyPressGetAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания ключа для платежной системы.
        /// </summary>
        internal static string EAdmKeySaleAsync {
            get {
                return ResourceManager.GetString("EAdmKeySaleAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при редактировании ключа.
        /// </summary>
        internal static string EAdmKeySaleEditAsync {
            get {
                return ResourceManager.GetString("EAdmKeySaleEditAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при получении данных ключа.
        /// </summary>
        internal static string EAdmKeySaleGetAsync {
            get {
                return ResourceManager.GetString("EAdmKeySaleGetAsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь не обладает правами на выполнение операции.
        ///Обратитесь к администратору базы данных..
        /// </summary>
        internal static string EAdmRightError {
            get {
                return ResourceManager.GetString("EAdmRightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка создания ключеовго слова md5.
        /// </summary>
        internal static string EAdmSetHashWord {
            get {
                return ResourceManager.GetString("EAdmSetHashWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попытка запуска второго экземпляра приложения.
        /// </summary>
        internal static string EAppDoubleApplication {
            get {
                return ResourceManager.GetString("EAppDoubleApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошбика получения списка карточек проекта.
        /// </summary>
        internal static string ECardList {
            get {
                return ResourceManager.GetString("ECardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при получении карточки.
        /// </summary>
        internal static string ECardLoad {
            get {
                return ResourceManager.GetString("ECardLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при удалении карточкек проекта.
        /// </summary>
        internal static string ECardUnoad {
            get {
                return ResourceManager.GetString("ECardUnoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при попыке выгрузить карточки в типографию.
        /// </summary>
        internal static string ECardUnoadToPress {
            get {
                return ResourceManager.GetString("ECardUnoadToPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка соединения с базой данных.
        /// </summary>
        internal static string EDbConnect {
            get {
                return ResourceManager.GetString("EDbConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя базы данных не должно быть пустым.
        /// </summary>
        internal static string EDbEmptyDbName {
            get {
                return ResourceManager.GetString("EDbEmptyDbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя сервера не должно быть пустым.
        /// </summary>
        internal static string EDbEmptyServerName {
            get {
                return ResourceManager.GetString("EDbEmptyServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин пользователя не может быть пустым.
        /// </summary>
        internal static string EDbEmptyUserName {
            get {
                return ResourceManager.GetString("EDbEmptyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Истек ключ действия сертификата доступа.
        /// </summary>
        internal static string EDbErrorCertificate {
            get {
                return ResourceManager.GetString("EDbErrorCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет доступа к базам выбранного сервера.
        /// </summary>
        internal static string EDbNotAccessToServer {
            get {
                return ResourceManager.GetString("EDbNotAccessToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр не может иметь значение Null.
        /// </summary>
        internal static string EDbNullParam {
            get {
                return ResourceManager.GetString("EDbNullParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка старта новой транзакции.
        /// </summary>
        internal static string EDbStartTransaction {
            get {
                return ResourceManager.GetString("EDbStartTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при удалении элементов спрвочника.
        /// </summary>
        internal static string EDcDeleteDictionary {
            get {
                return ResourceManager.GetString("EDcDeleteDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка добавления записи в справочник.
        /// </summary>
        internal static string EDcInsertDictionary {
            get {
                return ResourceManager.GetString("EDcInsertDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка открытия справочника.
        /// </summary>
        internal static string EDcOpenDictionary {
            get {
                return ResourceManager.GetString("EDcOpenDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошбика при попытке сохранения макета дизайна.
        /// </summary>
        internal static string EDcSaveDesign {
            get {
                return ResourceManager.GetString("EDcSaveDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при попытке сохранить пользователя.
        /// </summary>
        internal static string EDcSaveUser {
            get {
                return ResourceManager.GetString("EDcSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имена дизайнов не должны повторяться !.
        /// </summary>
        internal static string EDcUniqueDesign {
            get {
                return ResourceManager.GetString("EDcUniqueDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название юр. лица должно быть уникально !.
        /// </summary>
        internal static string EDcUniqueJuristic {
            get {
                return ResourceManager.GetString("EDcUniqueJuristic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Названия операций не должны повторяться !.
        /// </summary>
        internal static string EDcUniqueOperationName {
            get {
                return ResourceManager.GetString("EDcUniqueOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название платежной системы и ее префикс, должны быть уникальными !.
        /// </summary>
        internal static string EDcUniquePayment {
            get {
                return ResourceManager.GetString("EDcUniquePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Названия статусов не должны повторяться !.
        /// </summary>
        internal static string EDcUniqueStatusName {
            get {
                return ResourceManager.GetString("EDcUniqueStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя должно быть уникально !.
        /// </summary>
        internal static string EDcUniqueUserName {
            get {
                return ResourceManager.GetString("EDcUniqueUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка обновления элементов справочника.
        /// </summary>
        internal static string EDcUpdateDictionary {
            get {
                return ResourceManager.GetString("EDcUpdateDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не найден.
        /// </summary>
        internal static string EFileNotFound {
            get {
                return ResourceManager.GetString("EFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка открытия файла.
        /// </summary>
        internal static string EFileOpen {
            get {
                return ResourceManager.GetString("EFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Дизайн&quot; не должно быть пустым !.
        /// </summary>
        internal static string EMsgDesignEmpty {
            get {
                return ResourceManager.GetString("EMsgDesignEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В поле можно вводить только цифры !.
        /// </summary>
        internal static string EMsgDigitOnly {
            get {
                return ResourceManager.GetString("EMsgDigitOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Заказчик&quot; не должно быть пустым !.
        /// </summary>
        internal static string EMsgJuristicEmpty {
            get {
                return ResourceManager.GetString("EMsgJuristicEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Платежная система&quot; не должно быть пустым !.
        /// </summary>
        internal static string EMsgPaymentEmpty {
            get {
                return ResourceManager.GetString("EMsgPaymentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Имя проекта&quot; не может быть пустым !.
        /// </summary>
        internal static string EMsgProjectNameEmpty {
            get {
                return ResourceManager.GetString("EMsgProjectNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Номер проекта&quot; не может быть пустым !.
        /// </summary>
        internal static string EMsgProjectNumberEmpty {
            get {
                return ResourceManager.GetString("EMsgProjectNumberEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при удалении проекта.
        /// </summary>
        internal static string EPrDelete {
            get {
                return ResourceManager.GetString("EPrDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В файле найдены дубликаты номеров карт, уже внесенных в базу: {0}.
        /// </summary>
        internal static string EPrFileCardBaseDublicate {
            get {
                return ResourceManager.GetString("EPrFileCardBaseDublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В файле найдены дубликаты номеров карт.
        /// </summary>
        internal static string EPrFileCardDublicate {
            get {
                return ResourceManager.GetString("EPrFileCardDublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл должен содержать столбцы {0}.
        /// </summary>
        internal static string EPrFileCardHeader {
            get {
                return ResourceManager.GetString("EPrFileCardHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при создании проекта.
        /// </summary>
        internal static string EPrInsert {
            get {
                return ResourceManager.GetString("EPrInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка получения списка проектов.
        /// </summary>
        internal static string EPrList {
            get {
                return ResourceManager.GetString("EPrList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при получении проекта.
        /// </summary>
        internal static string EPrLoad {
            get {
                return ResourceManager.GetString("EPrLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при редактировании проекта.
        /// </summary>
        internal static string EPrUpdate {
            get {
                return ResourceManager.GetString("EPrUpdate", resourceCulture);
            }
        }
    }
}
